version: '3.8'

services:
  db:
    image: postgres:16.3-alpine
    container_name: dotgo-db
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} 
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - dotgo-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d {POSTGRES_DB}"]
      interval: 5s    # Verifica a cada 5 segundos
      timeout: 5s     # Considera falha se o comando demorar mais de 5s
      retries: 10     # Tenta 10 vezes antes de marcar como "unhealthy"
    networks:
      - dotgo-net

  app:
    build: .
    container_name: dotgo-app
    restart: always
    ports:
      - "${APP_PORT}:8080" 
    depends_on:
      db: # Garante que o banco de dados inicie antes da aplicação
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - dotgo-net
  
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: dotgo-tunnel
    restart: always
    depends_on:
      - app
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - dotgo-net

volumes:
  dotgo-data:

networks:
  dotgo-net:
    name: dotgo-network