version: '3.8'

services:
  # Serviço do Banco de Dados
  db:
    image: postgres:16.3-alpine
    container_name: dotgo-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres # Para produção, considere usar Docker Secrets
      - POSTGRES_DB=dotgo
    volumes:
      - dotgo-data:/var/lib/postgresql/data
    networks:
      - dotgo-network
    healthcheck:
      # Comando que o Docker executa para verificar a saúde do banco
      test: ["CMD-SHELL", "pg_isready -U postgres -d dotgo"]
      interval: 5s    # Verifica a cada 5 segundos
      timeout: 5s     # Considera falha se o comando demorar mais de 5s
      retries: 10     # Tenta 10 vezes antes de marcar como "unhealthy"

  # Serviço da Aplicação
  app:
    # IMPORTANTE: Não usamos 'build'. A imagem será baixada do Docker Hub.
    # O nome da imagem será passado por uma variável de ambiente pelo GitHub Actions.
    image: ${DOCKER_IMAGE}
    container_name: dotgo-app
    restart: always
    ports:
      - "8080:8080" # Mapeia a porta 8080 do container para a 8080 do servidor
    depends_on:
      db: # Garante que o banco de dados inicie antes da aplicação
        condition: service_healthy # <-- CONDIÇÃO ADICIONADA
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/dotgo
      - SPRING_DATASOURCE_USERNAME=dotgo
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - dotgo-network

volumes:
  dotgo-data:

networks:
  dotgo-network: