# .github/workflows/deploy.yml
name: CI/CD - Deploy da Aplicação Dotgo

on:
  push:
    branches: [ "main" ] # Aciona o workflow em cada push para a branch 'main'

# Adiciona o novo gatilho manual
  workflow_dispatch:


jobs:
  deploy:
    # Use o seu novo runner!
    runs-on: self-hosted

    steps:
      # Passo 1: O runner precisa do código do repositório
      - name: Checkout do código
        uses: actions/checkout@v4

      # Passo 2: Executar os comandos de deploy diretamente
      - name: Deploy da aplicação
        run: |
          echo "Iniciando deploy local..."
          
          # O runner já está na máquina certa, então os comandos são locais!
          # Navegue para o diretório do seu projeto
          cd /home/vignoli/Documentos/Projects/dotgo
          
          # Atualize o código
          git pull
          
          # Reconstrua e reinicie os containers
          docker-compose up -d --force-recreate --build
          
          echo "Deploy finalizado!"